version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
    - skip-changelog
    - dependencies
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
    - skip-changelog
    - dependencies
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    labels:
    - skip-changelog
    - dependencies
