blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://muhammad-fiaz.github.io/logly/
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/muhammad-fiaz/logly/discussions
    about: Ask questions and discuss ideas
