from __future__ import annotations

__version__: str

class PyLogger:
    def __init__(self) -> None: ...
    def add(self, sink: str, *, rotation: str | None = ...) -> int: ...
    def configure(self, level: str = ..., color: bool = ..., json: bool = ...) -> None: ...
    def remove(self, handler_id: int) -> bool: ...
    def trace(self, message: str, /, **kwargs) -> None: ...
    def debug(self, message: str, /, **kwargs) -> None: ...
    def info(self, message: str, /, **kwargs) -> None: ...
    def success(self, message: str, /, **kwargs) -> None: ...
    def warning(self, message: str, /, **kwargs) -> None: ...
    def error(self, message: str, /, **kwargs) -> None: ...
    def critical(self, message: str, /, **kwargs) -> None: ...
    def log(self, level: str, message: str, /, **kwargs) -> None: ...
    def complete(self) -> None: ...

logger: PyLogger
