name: Deploy Documentation

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-minify-plugin
          pip install pymdown-extensions
      
      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      
      - name: Build documentation
        run: mkdocs build --strict --verbose
      
      - name: Deploy to GitHub Pages (main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          mkdocs gh-deploy --force --clean --verbose --config-file mkdocs.yml --remote-branch gh-pages --remote-name origin
      
      - name: Upload artifact (PR preview)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: documentation-preview
          path: site/
          retention-days: 7
